Repository googleapis/java-securitycenter-settings, pull requests merged in 2020-06, with the labels that each got.

#60 chore: regenerate with updated protoc
  proto-google-cloud-securitycenter-settings-v1beta1/src/main/java/com/google/cloud/securitycenter/settings/v1beta1/BatchCalculateEffectiveSettingsRequest.java
  proto-google-cloud-securitycenter-settings-v1beta1/src/main/java/com/google/cloud/securitycenter/settings/v1beta1/BatchCalculateEffectiveSettingsResponse.java
  proto-google-cloud-securitycenter-settings-v1beta1/src/main/java/com/google/cloud/securitycenter/settings/v1beta1/BatchGetSettingsRequest.java
  proto-google-cloud-securitycenter-settings-v1beta1/src/main/java/com/google/cloud/securitycenter/settings/v1beta1/BatchGetSettingsResponse.java
  proto-google-cloud-securitycenter-settings-v1beta1/src/main/java/com/google/cloud/securitycenter/settings/v1beta1/BillingSettings.java
  proto-google-cloud-securitycenter-settings-v1beta1/src/main/java/com/google/cloud/securitycenter/settings/v1beta1/BillingTier.java
  proto-google-cloud-securitycenter-settings-v1beta1/src/main/java/com/google/cloud/securitycenter/settings/v1beta1/BillingType.java
  proto-google-cloud-securitycenter-settings-v1beta1/src/main/java/com/google/cloud/securitycenter/settings/v1beta1/CalculateEffectiveComponentSettingsRequest.java
  proto-google-cloud-securitycenter-settings-v1beta1/src/main/java/com/google/cloud/securitycenter/settings/v1beta1/CalculateEffectiveSettingsRequest.java
  proto-google-cloud-securitycenter-settings-v1beta1/src/main/java/com/google/cloud/securitycenter/settings/v1beta1/ComponentEnablementState.java
  proto-google-cloud-securitycenter-settings-v1beta1/src/main/java/com/google/cloud/securitycenter/settings/v1beta1/ComponentSettings.java
  proto-google-cloud-securitycenter-settings-v1beta1/src/main/java/com/google/cloud/securitycenter/settings/v1beta1/Detector.java
  proto-google-cloud-securitycenter-settings-v1beta1/src/main/java/com/google/cloud/securitycenter/settings/v1beta1/GetComponentSettingsRequest.java
  proto-google-cloud-securitycenter-settings-v1beta1/src/main/java/com/google/cloud/securitycenter/settings/v1beta1/GetServiceAccountRequest.java
  proto-google-cloud-securitycenter-settings-v1beta1/src/main/java/com/google/cloud/securitycenter/settings/v1beta1/GetSettingsRequest.java
  proto-google-cloud-securitycenter-settings-v1beta1/src/main/java/com/google/cloud/securitycenter/settings/v1beta1/ListComponentsRequest.java
  proto-google-cloud-securitycenter-settings-v1beta1/src/main/java/com/google/cloud/securitycenter/settings/v1beta1/ListComponentsResponse.java
  proto-google-cloud-securitycenter-settings-v1beta1/src/main/java/com/google/cloud/securitycenter/settings/v1beta1/ListDetectorsRequest.java
  proto-google-cloud-securitycenter-settings-v1beta1/src/main/java/com/google/cloud/securitycenter/settings/v1beta1/ListDetectorsResponse.java
  proto-google-cloud-securitycenter-settings-v1beta1/src/main/java/com/google/cloud/securitycenter/settings/v1beta1/ResetComponentSettingsRequest.java
  proto-google-cloud-securitycenter-settings-v1beta1/src/main/java/com/google/cloud/securitycenter/settings/v1beta1/ResetSettingsRequest.java
  proto-google-cloud-securitycenter-settings-v1beta1/src/main/java/com/google/cloud/securitycenter/settings/v1beta1/SecurityHealthAnalyticsSettings.java
  proto-google-cloud-securitycenter-settings-v1beta1/src/main/java/com/google/cloud/securitycenter/settings/v1beta1/ServiceAccount.java
  proto-google-cloud-securitycenter-settings-v1beta1/src/main/java/com/google/cloud/securitycenter/settings/v1beta1/Settings.java
  proto-google-cloud-securitycenter-settings-v1beta1/src/main/java/com/google/cloud/securitycenter/settings/v1beta1/SinkSettings.java
  proto-google-cloud-securitycenter-settings-v1beta1/src/main/java/com/google/cloud/securitycenter/settings/v1beta1/UpdateComponentSettingsRequest.java
  proto-google-cloud-securitycenter-settings-v1beta1/src/main/java/com/google/cloud/securitycenter/settings/v1beta1/UpdateSettingsRequest.java
  synth.metadata
Labels: automerge, cla: yes, context: full

#62 chore(java_templates): add default CODEOWNERS files for samples reviews
  .github/CODEOWNERS
  synth.metadata
Labels: automerge, cla: yes, context: full

#64 chore: turn on renovate-bot master issue for java repos
  renovate.json
  synth.metadata
Labels: automerge, cla: yes, context: full

#66 build(java): skip lint on samples directory
  .kokoro/build.sh
  synth.metadata
Labels: automerge, cla: yes, context: full

#74 fix: migrate securitycenter/settings/v1beta1 to grpc_service_config
  google-cloud-securitycenter-settings/src/main/java/com/google/cloud/securitycenter/settings/v1beta1/stub/SecurityCenterSettingsServiceStubSettings.java
  synth.metadata
Labels: cla: yes, context: full

#75 ci: switch to secret manager for sample/integration tests
  .kokoro/build.sh
  .kokoro/nightly/integration.cfg
  .kokoro/nightly/samples.cfg
  .kokoro/populate-secrets.sh
  .kokoro/presubmit/integration.cfg
  .kokoro/presubmit/samples.cfg
  .kokoro/trampoline.sh
  synth.metadata
Labels: automerge, cla: yes, context: full

#78 feat(deps): adopt flatten plugin and google-cloud-shared-dependencies
  .gitignore
  google-cloud-securitycenter-settings/pom.xml
  grpc-google-cloud-securitycenter-settings-v1beta1/pom.xml
  pom.xml
  proto-google-cloud-securitycenter-settings-v1beta1/pom.xml
  samples/install-without-bom/pom.xml
  samples/snapshot/pom.xml
  samples/snippets/pom.xml
Labels: cla: yes

#90 chore: regenerate README versions
  README.md
  synth.metadata
Labels: automerge, cla: yes, context: none
