Repository googleapis/java-securitycenter-settings, pull requests merged in 2020-09, with the labels that each got.

#109 build(java): switch to release-publish app for notifying GitHub of release status
  .kokoro/release/stage.cfg
  .kokoro/release/stage.sh
  synth.metadata
Labels: api: securitycenter, cla: yes, context: full

#115 build(ci): enable auto-release for dependency-update-only releases
  .github/workflows/auto-release.yaml
  synth.metadata
Labels: api: securitycenter, cla: yes, context: full

#116 chore: regenerate common templates
  README.md
  synth.metadata
Labels: cla: yes, context: none

#130 chore: add repo settings configuration
  .github/sync-repo-settings.yaml
Labels: api: securitycenter, automerge, cla: yes

#137 chore: regenerate templates
  .github/readme/synth.py
  .github/workflows/auto-release.yaml
  .kokoro/continuous/readme.cfg
  .kokoro/readme.sh
  synth.metadata
Labels: automerge, cla: yes, context: full

#139 build: rename samples lint workflow to checkstyle to disambiguate branch protection with unit lint
  .github/workflows/samples.yaml
  synth.metadata
Labels: automerge, cla: yes, context: full
