Repository googleapis/java-securitycenter-settings, pull requests merged in 2021-09, with the labels that each got.

#368 ci: removing linkage-monitor from the required checks
  .github/workflows/ci.yaml
  synth.metadata
Labels: automerge, cla: yes, api: securitycenter, context: full

#374 chore(java): install maven 3.8.1 at runtime
  .github/workflows/ci.yaml
  renovate.json
  synth.metadata
Labels: cla: yes, api: securitycenter, context: full

#372 chore: migrate to owlbot
  .github/.OwlBot.lock.yaml
  .github/.OwlBot.yaml
  .github/workflows/ci.yaml
  .kokoro/build.sh
  .kokoro/nightly/integration.cfg
  .kokoro/nightly/samples.cfg
  README.md
  google-cloud-securitycenter-settings-bom/pom.xml
  google-cloud-securitycenter-settings/pom.xml
  google-cloud-securitycenter-settings/src/main/java/com/google/cloud/securitycenter/settings/v1beta1/stub/SecurityCenterSettingsServiceStubSettings.java
  owlbot.py
  pom.xml
  synth.py
  versions.txt
Labels: automerge, cla: yes, api: securitycenter, owlbot:run

#378 chore: remove readme autosynth config
  .github/readme/synth.metadata/synth.metadata
  .github/workflows/ci.yaml
  .kokoro/build.sh
  .kokoro/nightly/integration.cfg
  .kokoro/nightly/samples.cfg
  README.md
  google-cloud-securitycenter-settings-bom/pom.xml
  versions.txt
Labels: automerge, kokoro:force-run, cla: yes, api: securitycenter

#379 chore: remove readme synth config
  .github/.OwlBot.lock.yaml
  .github/readme/synth.py
  .github/trusted-contribution.yml
  .github/workflows/ci.yaml
  .kokoro/continuous/readme.cfg
  .kokoro/release/common.sh
  .kokoro/release/drop.sh
  .kokoro/release/promote.sh
  .kokoro/release/publish_javadoc.sh
  .kokoro/release/publish_javadoc11.sh
  .kokoro/release/stage.sh
  .kokoro/trampoline.sh
Labels: cla: yes, api: securitycenter

#398 chore: change branch master to main in github configurations
  .github/sync-repo-settings.yaml
Labels: automerge, cla: yes, api: securitycenter

#387 chore: relocate owl bot post processor
  .github/.OwlBot.lock.yaml
  .github/.OwlBot.yaml
Labels: cla: yes, api: securitycenter
