Repository googleapis/java-securitycenter-settings, pull requests merged in 2021-08, with the labels that each got.

#346 feat!: release gapic-generator-java v2.0.0
  google-cloud-securitycenter-settings/src/main/java/com/google/cloud/securitycenter/settings/v1beta1/SecurityCenterSettingsServiceClient.java
  google-cloud-securitycenter-settings/src/main/java/com/google/cloud/securitycenter/settings/v1beta1/SecurityCenterSettingsServiceSettings.java
  google-cloud-securitycenter-settings/src/main/java/com/google/cloud/securitycenter/settings/v1beta1/stub/GrpcSecurityCenterSettingsServiceStub.java
  google-cloud-securitycenter-settings/src/main/java/com/google/cloud/securitycenter/settings/v1beta1/stub/SecurityCenterSettingsServiceStubSettings.java
  synth.metadata
Labels: cla: yes, api: securitycenter, context: full

#340 chore: remove java 7 units check
  .github/workflows/ci.yaml
  synth.metadata
Labels: automerge, cla: yes, api: securitycenter, context: full

#349 chore: remove java7 units check from required checks in master
  .github/sync-repo-settings.yaml
Labels: automerge, cla: yes, api: securitycenter

#354 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: automerge, cla: yes, api: securitycenter

#356 build(java): use ENABLE_FLAKYBOT env variable
  .kokoro/build.sh
  .kokoro/nightly/integration.cfg
  .kokoro/nightly/samples.cfg
  synth.metadata
Labels: automerge, cla: yes, api: securitycenter, context: full

#358 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: automerge, cla: yes, api: securitycenter

#366 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: automerge, cla: yes, api: securitycenter

#365 ci: removing linkage-monitor from the required checks
  .github/sync-repo-settings.yaml
Labels: automerge, cla: yes, api: securitycenter

#371 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: automerge, cla: yes, api: securitycenter
