Repository googleapis/java-securitycenter-settings, pull requests merged in 2021-05, with the labels that each got.

#299 build(java): switch to release-please for release tagging
  .github/release-please.yml
  synth.metadata
Labels: api: securitycenter, automerge, cla: yes, context: none

#300 chore: add enumeration data type to .repo-metadata.json
  .repo-metadata.json
Labels: api: securitycenter, automerge, cla: yes

#301 chore: adding cloud-rad java xrefs
  .kokoro/release/publish_javadoc11.sh
  synth.metadata
Labels: api: securitycenter, automerge, cla: yes, context: full

#304 build(java): remove codecov action
  .github/workflows/ci.yaml
  synth.metadata
Labels: api: securitycenter, automerge, cla: yes, context: full

#306 chore: add changelog to cloud-rad
  .kokoro/release/publish_javadoc11.sh
  synth.metadata
Labels: api: securitycenter, automerge, cla: yes, context: full

#308 feat: add `gcf-owl-bot[bot]` to `ignoreAuthors`
  .github/generated-files-bot.yml
  synth.metadata
Labels: api: securitycenter, automerge, cla: yes, context: full

#310 chore: dump maven version along with java
  .kokoro/build.sh
  synth.metadata
Labels: api: securitycenter, automerge, cla: yes, context: full
